fix #19
boswelja/compose-markdown pull request #20
Opened 2024-02-27 08:01 UTC by lolegrand

Note : I added support for inline content on Clickable text.

2024-02-27 08:48 UTC, boswelja commented
Sorry, I forgot to assign myself to the issue :sweat_smile: 
Twas fixed just now by https://github.com/boswelja/compose-markdown/pull/21

2024-02-27 08:48 UTC, boswelja commented
Actually if you want to rebase it, `LocalUriHandler` seems like a much better solution!

2024-02-27 13:19 UTC, lolegrand commented
Do you want to keep your onClick event bubbleing up to the document or should I remove the onClickLink event.

Note : Maybe we should support the navigation in app. Like if a markdown document is loaded in a view and some links allow user to navigate to other screen.

2024-02-27 21:36 UTC, boswelja commented
> Do you want to keep your onClick event bubbleing up to the document or should I remove the onClickLink event ?
> 
> Note : Maybe we should support the navigation in app. Like if a markdown document is loaded in a view and some links allow user to navigate to other screen.

I think keeping the `onLinkClick` event is a good idea, it'd also let users customize the link navigation behavior like you said

2024-02-28 07:51 UTC, lolegrand commented
I have done the modification.

You can merge if it suite you.

2024-02-28 10:02 UTC, boswelja requested changes
Please also remove the androidx-browser dependency

2024-02-28 10:02 UTC, boswelja commented on material3/src/androidMain/kotlin/com/boswelja/markdown/material3/UrlLauncher.kt
>  public actual fun rememberUrlLauncher(): UrlLauncher {
We can probably just ditch the whole UrlLauncher thing, what do you think?

2024-02-28 10:10 UTC, lolegrand commented on material3/src/androidMain/kotlin/com/boswelja/markdown/material3/UrlLauncher.kt
>  public actual fun rememberUrlLauncher(): UrlLauncher {
Yes, we can. I leave it here because I was thinking about handling deeplLink to navigate in another app.

But apparently it's handled the same way as http URI.

2024-02-28 10:20 UTC, lolegrand commented
As you said I deleted the Url abstraction part.

I also remarqued that the event wasn't bubbling up to the material3 Markdown document. 

I added the event and let the choice to the user to override the handler. 

What do you think of it ?

2024-02-28 10:57 UTC, boswelja approved these changes
Looks good to me, thanks!

2024-02-28 11:04 UTC, lolegrand commented
Thanks !

I don't think I have the right to merge it. Anyhow, I will let you merge it with your next release.

Have a great week 👍

2024-02-28 11:50 UTC, merged